#!/usr/bin/env bash
# script that configures a new Ubuntu machine to install nginx server
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
service nginx status
