#!/usr/bin/env bash
# Redirection of my server
apt-get -y update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www
sudo chmod -R 755 /var/www
rm -rf /var/www/html/*
echo "Hello World!" > /var/www/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.html;
    location /redirect_me {
        return 301 https://modtechy.ke/;
    }
}" > /etc/nginx/sites-available/default
