#!/usr/bin/env bash
# config a 404 page in nginx server

apt-get -y update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
chown -R "$USER":"$USER" /var/www/
chmod -R 755 /var/www/
rm -rf /var/www/html/*
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
service nginx start
service nginx status

printf %s "server {
    listen 80;
    listen [::]:80 default_server;

    root    /var/www/html;

    index index.html index.htm;

    location /redirect_me {
        return 301 https://modtechy.ke/;
    }

    error_page 404 /404.html;

    location /404 {
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
